services:
  backend:
    image: audit-listener
    build:
      context: .
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_USERNAME: elastic
      SPRING_ELASTICSEARCH_PASSWORD: ${ES_PASSWORD}
    ports:
      - "8081:8081"

  elasticsearch:
    image: elasticsearch:8.19.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -u elastic:${ES_PASSWORD} http://localhost:9200 > /dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - es-data:/usr/share/elasticsearch/data

  es-init:
    image: curlimages/curl:8.5.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
      sh -c "
      curl -s -u elastic:${ES_PASSWORD} -X PUT http://elasticsearch:9200/audit-methods -H 'Content-Type: application/json' -d @/scripts/audit-methods.json &&
      curl -s -u elastic:${ES_PASSWORD} -X PUT http://elasticsearch:9200/audit-requests -H 'Content-Type: application/json' -d @/scripts/audit-requests.json
      "
    volumes:
      - ./scripts:/scripts

volumes:
  es-data: