spring:
  application:
    name: audit-listener
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: password123

server:
  port: 8081

audit:
  kafka:
    topic:
      requestsTopic: audit.requests
      methodsTopic: audit.methods